import type { MetadataRoute } from 'next'

/**
 * Web app manifest — makes Eagle Eye Africa installable (home-screen icon,
 * standalone display, themed browser chrome). Icons are committed PNGs
 * generated by `node scripts/generate-pwa-icons.mjs`.
 *
 * Root-level metadata route (not a user-facing page): installability is
 * locale-independent, so a single manifest serves both locales.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Eagle Eye Africa — Community News, Photo Stories & More',
    short_name: 'EEA',
    description:
      'A community-first African media platform: local journalism, photo stories, community notices, buy & sell and culture.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#0f172a',
    theme_color: '#0f172a',
    icons: [
      {
        src: '/icons/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: '/icons/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
      },
      {
        src: '/icons/icon-512-maskable.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  }
}
